### PR TITLE
Add fix gif

### PR DESCRIPTION
**Pull request by styfle**
Because it's that kind of day

https://gifs-3lfl6s0t1.now.sh/fix

### CODE REVIEW

**Comment by styfle** [comment]
fix

**Comment by styfle** [comment]
cc @matheuss

**Comment by matheuss** [comment]
I don't like it @styfle 🤔 What does it mean 🤔

**Comment by styfle** [comment]
You start fixing one thing and get distracted fixing another thing

https://www.youtube.com/watch?v=AbSehcT19u0

**Comment by styfle** [comment]
Just a friendly ping 😄  @matheuss

**Comment by matheuss** [comment]
@styfle sorry, but I don't like it 😕 As per the repo description, it's a highly optioned repository. I'll clarify on the readme

**Comment by matheuss** [comment]
Done https://github.com/matheuss/gifs/tree/master#can-i-add-a-gif-i-like

**Pull request closed without merging**
